"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { apiFetch } from "@/lib/api";
import type { Profile } from "@/lib/types";

function StatIcon({ kind }: { kind: "gem" | "fire" | "heart" | "star" }) { const colors = { gem: "#1cb0f6", fire: "#ff9600", heart: "#ff4b4b", star: "#58cc02" }; const paths = { gem: <path d="m12 3 8 5v8l-8 5-8-5V8l8-5Z"/>, fire: <path d="M12 22c4.1 0 7-2.9 7-7.1 0-3.2-2.2-5.4-4.5-7.9.2 2.4-1.2 3.7-2.6 4.6C12.1 7.8 9.5 5.5 8 3c-2.8 3.2-3 6.7-3 9.3C5 18.1 8 22 12 22Z"/>, heart: <path d="M12 20.5 4.5 13C1.7 10.2 2.3 5.5 6.2 4.3c2-.6 4.2.1 5.8 2 1.6-1.9 3.8-2.6 5.8-2C21.7 5.5 22.3 10.2 19.5 13Z"/>, star: <path d="m12 2.8 2.7 5.6 6.2.9-4.5 4.4 1.1 6.2-5.5-3-5.5 3 1.1-6.2-4.5-4.4 6.2-.9Z"/> }; return <svg viewBox="0 0 24 24" aria-hidden="true" className="h-8 w-8" fill={colors[kind]}>{paths[kind]}</svg>; }

export default function ProfilePage() {
  const [profile, setProfile] = useState<Profile | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  useEffect(() => { async function load() { try { setProfile(await apiFetch<Profile>("/api/profile")); } catch (err) { console.error(err); setError("Could not load your profile."); } finally { setLoading(false); } } load(); }, []);
  if (loading) return <main className="grid min-h-screen place-items-center bg-[#f7f7f7] font-bold text-slate-500">Loading your profile...</main>;
  if (error || !profile) return <main className="grid min-h-screen place-items-center bg-[#f7f7f7] font-bold text-slate-500"><div className="text-center"><p>{error ?? "Something went wrong."}</p><Link href="/" className="mt-4 inline-block font-extrabold text-[#58cc02]">Back to dashboard</Link></div></main>;
  const { stats, progress } = profile; const dailyPct = stats.daily_xp_goal > 0 ? Math.min(100, stats.daily_xp_earned / stats.daily_xp_goal * 100) : 0;
  const cards = [{ label: "Total XP", value: stats.xp_total, icon: "gem" as const }, { label: "Day streak", value: stats.streak_count, icon: "fire" as const }, { label: "Hearts", value: `${stats.hearts}/${stats.hearts_max}`, icon: "heart" as const }, { label: "Skills complete", value: progress.skills_completed, icon: "star" as const }];
  return <main className="min-h-screen bg-[#f7f7f7]"><header className="border-b-2 border-slate-100 bg-white"><div className="mx-auto flex max-w-4xl items-center justify-between px-6 py-5"><Link href="/" className="text-3xl font-black tracking-tight text-[#58cc02]">lingua</Link><Link href="/" className="rounded-xl px-4 py-2 text-sm font-extrabold uppercase text-slate-500 hover:bg-slate-50">Back to learn</Link></div></header><section className="mx-auto max-w-3xl px-6 py-12"><div className="mb-8 flex items-center gap-5 rounded-3xl bg-[#58cc02] p-7 text-white shadow-[0_6px_0_#46a302]"><div className="grid h-16 w-16 place-items-center rounded-full bg-white text-3xl font-black text-[#58cc02]">{profile.username.charAt(0).toUpperCase()}</div><div><p className="text-sm font-extrabold uppercase tracking-wide text-[#d7ffb8]">Learner profile</p><h1 className="text-3xl font-black">{profile.username}</h1></div></div><div className="mb-8 grid grid-cols-2 gap-4 sm:grid-cols-4">{cards.map((card) => <article key={card.label} className="rounded-3xl border-2 border-slate-200 bg-white p-5 text-center"><div className="mx-auto grid h-11 w-11 place-items-center rounded-2xl bg-slate-50"><StatIcon kind={card.icon} /></div><p className="mt-3 text-2xl font-black text-slate-700">{card.value}</p><p className="mt-1 text-xs font-extrabold uppercase tracking-wide text-slate-400">{card.label}</p></article>)}</div><section className="mb-6 rounded-3xl border-2 border-slate-200 bg-white p-7"><div className="mb-4 flex items-center justify-between"><h2 className="text-xl font-black text-slate-700">Daily XP goal</h2><span className="font-extrabold text-[#1cb0f6]">{stats.daily_xp_earned} / {stats.daily_xp_goal} XP</span></div><div className="h-5 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-[#58cc02]" style={{ width: `${dailyPct}%` }} /></div></section><section className="rounded-3xl border-2 border-slate-200 bg-white p-7"><h2 className="text-xl font-black text-slate-700">Learning progress</h2><div className="mt-5 grid grid-cols-2 gap-5"><div className="rounded-2xl bg-[#ddf4ff] p-5"><p className="text-2xl font-black text-[#168ac2]">{progress.skills_completed}</p><p className="mt-1 font-bold text-slate-500">Skills completed</p></div><div className="rounded-2xl bg-[#fff4d2] p-5"><p className="text-2xl font-black text-[#d99500]">{progress.lessons_completed}</p><p className="mt-1 font-bold text-slate-500">Lessons completed</p></div></div></section></section></main>;
}
